include:
  - template: Code-Quality.gitlab-ci.yml

image:
  python:3.10-bullseye

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

unit-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Running unit tests..."
    - coverage run --source=tap_mambu/tap_mambu_refactor -m pytest tests/refactor_unittests
    - coverage json
    - python3 -c "import json; coverage_json = json.loads(open('coverage.json', 'r').read()); print('Coverage is', round(coverage_json['totals']['percent_covered'], 2))"

lint-test-job:
  stage: test
  before_script:
    - python3 -m pip install --upgrade -r requirements.txt
    - python3 -m pip install --upgrade -r requirements_ci.txt
  script:
    - echo "Linting code..."
    - pylint tap_mambu/tap_mambu_refactor --exit-zero
    - pylint tap_mambu/tap_mambu_refactor -d C -d R -d W || true
